---
- name: Install packages
  yum:
    name:
      - postfix
      - cyrus-sasl-plain
      - s-nail
      - mutt
    state: present
  become: true

- name: Enable and start postfix
  service:
    name: postfix
    state: started
    enabled: true
  become: true

- name: Edit config file
  blockinfile:
    path: /etc/postfix/main.cf
    block: |
      myhostname = {{ ansible_facts.hostname }}.{{ domain }}
      relayhost = [{{ smtp_server }}]:{{ smtp_port }}
      smtp_use_tls = yes
      smtp_sasl_auth_enable = yes
      smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
      smtp_sasl_security_options = noanonymous
      smtp_sasl_tls_security_options = noanonymous
  become: true
  notify: Reload and send

- name: Edit Postfix SMTP authentication file
  template:
    src: sasl_passwd.j2
    dest: /etc/postfix/sasl_passwd
    owner: root
    group: postfix
    mode: 0640
  register: sasl_passwd
  become: true
  notify: Reload and send

- name: Generate the postmap file
  shell: "postmap /etc/postfix/sasl_passwd"
  become: true
  when: sasl_passwd.changed

- name: Create roots .muttrc file
  template:
    src: muttrc.j2
    dest: "{{ mutt_rc_path }}"
  become: true
  when: mutt_create_roots_muttrc
